### ISSUE TITLE
What exatcly does the "latest" option refer to?

### ISSUE THREAD

**Issue by EPNW** [apache/mynewt-documentation#102]
I was about to cite [HAL page of the manual](https://mynewt.apache.org/latest/os/modules/hal/hal.html) in an essay. For this, I need to be able to exactly describe the version I'm refereing to. The version drop down allows me to select different versions, either a specific one (e.g. 1.7.0, 1.6.0) or "latest". Obviously, I can not cite "latest", because the version "latest" is refering to will change in the future. I need to cite something like "1.8.0". Could we change the "latest" option in the version dropdown to "1.8.0 (latest)" (assuming 1.8.0 is currently latest, which I don't know, since the version drop down tells me nothing about the latest version)?

**Comment by caspermeijn** [comment]
I am not sure what you mean with version dropdown. At https://mynewt.apache.org/documentation/ I see a link to the v1.8.0 of the documentation.

I believe that the "latest" documentation is generated from the master branch and that the  "v1.8.0" documenation is generated from the v1.8.0 tag of mynewt.

Does that answer your question?

**Comment by EPNW** [comment]
I'm not sure about this: Once you select "1.8.0" on the page you mention and inspect the version dropdown on the page you land on, there is no entry for "1.8.0", only "latest" and from "1.7.0" downwards. So either "1.8.0" is not accessible from the dropdown, or "latest" actually refers to "1.8.0". But I don't think that the later is the case, since when you go to [https://mynewt.apache.org/v1_8_0/](https://mynewt.apache.org/v1_8_0/) (what is again, unavailable from the version dropdown), you get a warning that "Version 1.8.0 is not the most recent version of the Apache Mynewt documentation."

With version dropdown I mean this:
![latest](https://user-images.githubusercontent.com/30860236/100197769-18a3f780-2efb-11eb-828f-264f285da596.png)

**Comment by caspermeijn** [comment]
You are right, the dropdown was not updated. This will be fixed by https://github.com/apache/mynewt-documentation/pull/103

So latest is the master branch of mynewt and the specific version are tagged releases of mynewt. v1.8.0 is the most recent release. I believe there are plans to release v1.9 in a few months.

**Comment by utzig** [comment]
The reported issues were fixed for the moment being, now there is "1.8.0" and "latest". It happened due to Apache moving its build infrastructure to new servers, which disabled the auto publishing of site content when our repos are updated, so they ended up stale. I pushed a new site manually this time, but a new Jenkins site publishing must be set up soon. I am closing this, feel free to reopen if issues persist.
